import json

NB_PATH = "c:/Users/david/Desktop/project_ssl/Omnilex-Agentic-Retrieval-Competition/notebooks/02_agentic_retrieval_baseline.ipynb"

DIAG_SOURCE = [
    "import time\n",
    "import textwrap\n",
    "\n",
    "# ── Diagnostic configuration ──────────────────────────────────────────\n",
    "DIAG_N       = 3    # number of val queries to diagnose\n",
    "ORACLE_K     = 10   # BM25 top-K for oracle recall\n",
    "TIMEOUT_SEC  = 180  # flag as timeout if agent exceeds this\n",
    "\n",
    "\n",
    "def _tokens(text: str) -> int:\n",
    "    return max(1, len(text) // 4)\n",
    "\n",
    "\n",
    "def _oracle_recall(query: str, gold: list[str], k: int) -> dict:\n",
    "    \"\"\"What fraction of gold citations appear in BM25 top-K?\"\"\"\n",
    "    law_hits   = {r['citation'] for r in laws_index.search(query, top_k=k)}\n",
    "    court_hits = {r['citation'] for r in courts_index.search(query, top_k=k)}\n",
    "    all_hits   = law_hits | court_hits\n",
    "    gold_set   = set(gold)\n",
    "    found      = gold_set & all_hits\n",
    "    return {\n",
    "        'recall':      len(found) / len(gold_set) if gold_set else 0.0,\n",
    "        'found':       sorted(found),\n",
    "        'missed':      sorted(gold_set - all_hits),\n",
    "        'law_found':   sorted(gold_set & law_hits),\n",
    "        'court_found': sorted(gold_set & court_hits),\n",
    "    }\n",
    "\n",
    "\n",
    "def _run_timed(query: str):\n",
    "    \"\"\"Run agent; return (citations, logs, elapsed_sec, flagged_timeout).\"\"\"\n",
    "    t0 = time.time()\n",
    "    try:\n",
    "        cits, logs = run_agent(query, verbose=False)\n",
    "        elapsed    = time.time() - t0\n",
    "        return cits, logs, elapsed, elapsed > TIMEOUT_SEC\n",
    "    except Exception:\n",
    "        return [], [], time.time() - t0, True\n",
    "\n",
    "\n",
    "# ── Main diagnostic loop ───────────────────────────────────────────────\n",
    "if not IS_VALIDATION_MODE or 'gold_citations' not in test_df.columns:\n",
    "    print('Diagnosis requires validation mode with gold_citations.')\n",
    "else:\n",
    "    sample_df = test_df.head(DIAG_N).reset_index(drop=True)\n",
    "    lines     = []\n",
    "    SEP_H     = '=' * 72\n",
    "    SEP_L     = '-' * 72\n",
    "\n",
    "    lines += [\n",
    "        SEP_H,\n",
    "        '  FAILURE DIAGNOSIS REPORT',\n",
    "        f\"  Generated : {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}\",\n",
    "        f\"  Queries   : {DIAG_N}   Oracle-K : {ORACLE_K}   Timeout : {TIMEOUT_SEC}s\",\n",
    "        SEP_H,\n",
    "    ]\n",
    "\n",
    "    summary_rows = []\n",
    "\n",
    "    for _, row in sample_df.iterrows():\n",
    "        qid      = row['query_id']\n",
    "        query    = row['query']\n",
    "        gold_str = row.get('gold_citations', '')\n",
    "        gold     = [c.strip() for c in gold_str.split(';') if c.strip()]\n",
    "\n",
    "        lines += ['', SEP_L, f'  QUERY  {qid}', SEP_L]\n",
    "        lines.append(textwrap.fill(query, width=70, initial_indent='  '))\n",
    "\n",
    "        # Gold citations\n",
    "        lines += [f'\\n  GOLD CITATIONS  ({len(gold)} total)']\n",
    "        for g in gold:\n",
    "            lines.append(f'    . {g}')\n",
    "\n",
    "        # BM25 oracle recall\n",
    "        oracle = _oracle_recall(query, gold, k=ORACLE_K)\n",
    "        lines += [\n",
    "            f\"\\n  BM25 ORACLE RECALL@{ORACLE_K}  ->  \"\n",
    "            f\"{oracle['recall']:.0%}  ({len(oracle['found'])}/{len(gold)} gold retrievable)\",\n",
    "        ]\n",
    "        if oracle['law_found']:\n",
    "            lines.append(f\"    Law hits   : {oracle['law_found']}\")\n",
    "        if oracle['court_found']:\n",
    "            lines.append(f\"    Court hits : {oracle['court_found']}\")\n",
    "        if oracle['missed']:\n",
    "            lines.append(f\"    MISSED     : {oracle['missed']}\")\n",
    "\n",
    "        # Run agent\n",
    "        lines.append('\\n  RUNNING AGENT ...')\n",
    "        cits, logs, elapsed, flagged = _run_timed(query)\n",
    "\n",
    "        status = f'TIMEOUT (>{TIMEOUT_SEC}s)' if flagged else 'COMPLETED'\n",
    "        lines.append(f'  STATUS  {status}  ({elapsed:.1f}s)')\n",
    "\n",
    "        # Raw citations extracted\n",
    "        gold_set = set(gold)\n",
    "        lines += [f'\\n  RAW CITATIONS EXTRACTED  ({len(cits)})']\n",
    "        for c in cits:\n",
    "            tag = 'CORRECT' if c in gold_set else 'wrong'\n",
    "            lines.append(f'    [{tag}] {c}')\n",
    "        if not cits:\n",
    "            lines.append('    (none)')\n",
    "\n",
    "        # Observation token breakdown\n",
    "        obs_logs         = [lg for lg in logs if lg.get('type') == 'tool_execution']\n",
    "        total_obs_tokens = sum(_tokens(lg.get('observation', '')) for lg in obs_logs)\n",
    "        lines += [f'\\n  OBSERVATION TOKENS  (est. total: {total_obs_tokens})']\n",
    "        for lg in obs_logs:\n",
    "            toks = _tokens(lg.get('observation', ''))\n",
    "            q50  = lg['query'][:50]\n",
    "            lines.append(f\"    {lg['tool']:15s}  query='{q50}'  -> {toks} tok\")\n",
    "\n",
    "        # Failure mode flags\n",
    "        correct    = [c for c in cits if c in gold_set]\n",
    "        f_retrieve = oracle['recall'] == 0.0\n",
    "        f_partial  = 0.0 < oracle['recall'] < 0.5\n",
    "        f_extract  = oracle['recall'] > 0 and len(correct) == 0\n",
    "        f_context  = total_obs_tokens > 2000\n",
    "        f_timeout  = flagged\n",
    "\n",
    "        lines += ['\\n  FAILURE MODE FLAGS']\n",
    "        lines.append(f\"    Retrieval failure  (0% oracle)           : {'YES <<' if f_retrieve else 'no'}\")\n",
    "        lines.append(f\"    Partial retrieval  (<50% oracle)         : {'YES <<' if f_partial  else 'no'}\")\n",
    "        lines.append(f\"    Extraction failure (BM25 found, missed)  : {'YES <<' if f_extract  else 'no'}\")\n",
    "        lines.append(f\"    Context bloat      (obs tokens >2000)    : {'YES <<' if f_context  else 'no'} ({total_obs_tokens} tok)\")\n",
    "        lines.append(f\"    Timeout                                  : {'YES <<' if f_timeout  else 'no'}\")\n",
    "\n",
    "        dominant = (\n",
    "            'RETRIEVAL'  if f_retrieve else\n",
    "            'EXTRACTION' if f_extract  else\n",
    "            'TIMEOUT'    if f_timeout  else\n",
    "            'CONTEXT'    if f_context  else\n",
    "            'OK'\n",
    "        )\n",
    "        summary_rows.append({\n",
    "            'id':         qid,\n",
    "            'oracle':     f\"{oracle['recall']:.0%}\",\n",
    "            'extracted':  len(cits),\n",
    "            'correct':    len(correct),\n",
    "            'obs_tokens': total_obs_tokens,\n",
    "            'elapsed':    f'{elapsed:.0f}s',\n",
    "            'dominant':   dominant,\n",
    "        })\n",
    "\n",
    "    # Summary table\n",
    "    lines += ['', SEP_H, '  SUMMARY', SEP_H]\n",
    "    lines.append(f\"  {'ID':<12} {'Oracle':>8} {'Extracted':>10} {'Correct':>8} {'ObsTok':>8} {'Time':>7}  Dominant\")\n",
    "    lines.append('  ' + '-' * 66)\n",
    "    for r in summary_rows:\n",
    "        lines.append(\n",
    "            f\"  {r['id']:<12} {r['oracle']:>8} {r['extracted']:>10} \"\n",
    "            f\"{r['correct']:>8} {r['obs_tokens']:>8} {r['elapsed']:>7}  {r['dominant']}\"\n",
    "        )\n",
    "\n",
    "    dominant_counts = {}\n",
    "    for r in summary_rows:\n",
    "        dominant_counts[r['dominant']] = dominant_counts.get(r['dominant'], 0) + 1\n",
    "    lines += ['', '  Dominant failure mode across all queries:']\n",
    "    for mode, cnt in sorted(dominant_counts.items(), key=lambda x: -x[1]):\n",
    "        lines.append(f'    {mode}: {cnt}/{DIAG_N}')\n",
    "    lines += ['', SEP_H, '']\n",
    "\n",
    "    report = '\\n'.join(lines)\n",
    "    print(report)\n",
    "\n",
    "    out = OUTPUT_PATH / 'failure_diagnosis.txt'\n",
    "    out.write_text(report, encoding='utf-8')\n",
    "    print(f'Report saved -> {out}')\n",
]

nb = json.load(open(NB_PATH, encoding="utf-8"))

header_cell = {
    "cell_type": "markdown",
    "metadata": {},
    "source": "## 10. Failure Diagnosis\n\nRuns 3 sample queries and diagnoses which failure mode dominates: retrieval gap, extraction failure, context bloat, or timeout."
}

diag_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": DIAG_SOURCE
}

# Insert before the Summary markdown (currently at index 26)
nb["cells"].insert(26, diag_cell)
nb["cells"].insert(26, header_cell)

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Done. Notebook now has {len(nb['cells'])} cells.")
print(f"Diagnostic cells inserted at positions 26-27.")
