import json

NB_PATH = "c:/Users/david/Desktop/project_ssl/Omnilex-Agentic-Retrieval-Competition/notebooks/02_agentic_retrieval_baseline.ipynb"

SOURCE = [
    "# ── Corpus Coverage Diagnosis — no changes made ─────────────────────────\n",
    "import re, os\n",
    "from collections import Counter\n",
    "from pathlib import Path\n",
    "\n",
    "SEP = '=' * 72\n",
    "sep = '-' * 72\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────\n",
    "# STEP 1 — Law abbreviation frequency table\n",
    "# ─────────────────────────────────────────────────────────────────────────\n",
    "print(SEP)\n",
    "print('  STEP 1 — LAW ABBREVIATION COVERAGE')\n",
    "print(SEP)\n",
    "\n",
    "TARGET_LAWS = ['StPO', 'BGG', 'StGB', 'StBOG', 'ZGB', 'BV', 'ATSG', 'IVG', 'BGerR']\n",
    "\n",
    "def _extract_law_abbr(cit: str) -> str:\n",
    "    \"\"\"Last whitespace-delimited token, stripped of trailing punctuation.\"\"\"\n",
    "    tokens = cit.strip().split()\n",
    "    return re.sub(r'[^A-Za-z0-9äöüÄÖÜ]', '', tokens[-1]) if tokens else ''\n",
    "\n",
    "law_abbr_counts = Counter(\n",
    "    _extract_law_abbr(doc.get('citation', '')) for doc in laws_index.documents\n",
    ")\n",
    "law_abbr_counts.pop('', None)  # remove empty\n",
    "\n",
    "ranked = law_abbr_counts.most_common()\n",
    "print(f'\\n  Total unique law abbreviations in index: {len(ranked)}')\n",
    "print(f'  Total documents in laws index          : {len(laws_index.documents):,}')\n",
    "\n",
    "print('\\n  Top-30 abbreviations (by document count):')\n",
    "print(f'  {\"Abbr\":<15} {\"Count\":>8}')\n",
    "print(f'  {\"-\"*15} {\"-\"*8}')\n",
    "for abbr, cnt in ranked[:30]:\n",
    "    flag = '  <<< TARGET' if abbr in TARGET_LAWS else ''\n",
    "    print(f'  {abbr:<15} {cnt:>8}{flag}')\n",
    "\n",
    "print('\\n  Bottom-20 abbreviations (rarest):')\n",
    "print(f'  {\"Abbr\":<15} {\"Count\":>8}')\n",
    "print(f'  {\"-\"*15} {\"-\"*8}')\n",
    "for abbr, cnt in ranked[-20:]:\n",
    "    flag = '  <<< TARGET' if abbr in TARGET_LAWS else ''\n",
    "    print(f'  {abbr:<15} {cnt:>8}{flag}')\n",
    "\n",
    "print('\\n  Target law coverage check:')\n",
    "for abbr in TARGET_LAWS:\n",
    "    cnt = law_abbr_counts.get(abbr, 0)\n",
    "    status = f'{cnt:>6} documents' if cnt else 'ABSENT'\n",
    "    print(f'  {abbr:<10} : {status}')\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────\n",
    "# STEP 2 — Court series frequency table\n",
    "# ─────────────────────────────────────────────────────────────────────────\n",
    "print(f'\\n{SEP}')\n",
    "print('  STEP 2 — COURT DECISION SERIES COVERAGE')\n",
    "print(SEP)\n",
    "\n",
    "def _extract_court_prefix(cit: str) -> str:\n",
    "    cit = cit.strip()\n",
    "    if cit.startswith('BGE'):\n",
    "        return 'BGE'\n",
    "    # docket style: '1B_90/2021 E. 2.1' -> '1B'\n",
    "    m = re.match(r'^([0-9]+[A-Za-z]+)', cit)\n",
    "    if m:\n",
    "        return m.group(1)\n",
    "    return cit.split('_')[0] if '_' in cit else cit.split('/')[0]\n",
    "\n",
    "court_prefix_counts = Counter(\n",
    "    _extract_court_prefix(doc.get('citation', '')) for doc in courts_index.documents\n",
    ")\n",
    "court_prefix_counts.pop('', None)\n",
    "\n",
    "court_ranked = court_prefix_counts.most_common()\n",
    "print(f'\\n  Total unique court prefixes in index: {len(court_ranked)}')\n",
    "print(f'  Total documents in courts index     : {len(courts_index.documents):,}')\n",
    "\n",
    "print('\\n  All prefixes (by count):')\n",
    "print(f'  {\"Prefix\":<12} {\"Count\":>10}')\n",
    "print(f'  {\"-\"*12} {\"-\"*10}')\n",
    "for prefix, cnt in court_ranked:\n",
    "    print(f'  {prefix:<12} {cnt:>10}')\n",
    "\n",
    "# Specific checks\n",
    "print('\\n  Specific existence checks:')\n",
    "checks = [\n",
    "    ('BGE 137',   lambda c: c.startswith('BGE 137')),\n",
    "    ('BGE 139',   lambda c: c.startswith('BGE 139')),\n",
    "    ('BGE 143',   lambda c: c.startswith('BGE 143')),\n",
    "    ('1B_90',     lambda c: '1B_90' in c),\n",
    "    ('7B_496',    lambda c: '7B_496' in c),\n",
    "    ('1B_ any',   lambda c: re.match(r'^1B_', c) is not None),\n",
    "    ('7B_ any',   lambda c: re.match(r'^7B_', c) is not None),\n",
    "]\n",
    "all_court_cits = [doc.get('citation', '') for doc in courts_index.documents]\n",
    "for label, fn in checks:\n",
    "    matches = [c for c in all_court_cits if fn(c)]\n",
    "    status  = f'{len(matches):>6} entries' if matches else 'ABSENT'\n",
    "    sample  = f'  e.g. {matches[0]}' if matches else ''\n",
    "    print(f'  {label:<12}: {status}{sample}')\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────\n",
    "# STEP 3 — Data directory file tree\n",
    "# ─────────────────────────────────────────────────────────────────────────\n",
    "print(f'\\n{SEP}')\n",
    "print('  STEP 3 — COMPETITION DATA FILE TREE')\n",
    "print(SEP)\n",
    "\n",
    "search_roots = [\n",
    "    DATA_PATH,\n",
    "    DATA_PATH.parent,\n",
    "    Path('/kaggle/input'),\n",
    "    Path('../input'),\n",
    "    Path('./input'),\n",
    "]\n",
    "\n",
    "for root in search_roots:\n",
    "    if not root.exists():\n",
    "        continue\n",
    "    print(f'\\n  {root}  (exists):')\n",
    "    try:\n",
    "        entries = sorted(root.rglob('*'))\n",
    "        for p in entries:\n",
    "            if p.is_file():\n",
    "                try:\n",
    "                    size_mb = p.stat().st_size / 1e6\n",
    "                    indent  = '  ' + '  ' * (len(p.relative_to(root).parts) - 1)\n",
    "                    print(f'{indent}  {p.name:<50}  {size_mb:>9.2f} MB')\n",
    "                except Exception:\n",
    "                    print(f'    {p}')\n",
    "            elif p.is_dir():\n",
    "                indent = '  ' + '  ' * (len(p.relative_to(root).parts) - 1)\n",
    "                print(f'{indent}  [{p.name}/]')\n",
    "    except PermissionError:\n",
    "        print('    (permission denied)')\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────\n",
    "# STEP 4 — Sample documents from index\n",
    "# ─────────────────────────────────────────────────────────────────────────\n",
    "print(f'\\n{SEP}')\n",
    "print('  STEP 4 — SAMPLE DOCUMENTS FROM INDEX')\n",
    "print(SEP)\n",
    "\n",
    "# Laws: find StPO docs, fallback to any Art. doc\n",
    "stpo_docs = [d for d in laws_index.documents if 'StPO' in d.get('citation', '')]\n",
    "fallback_docs = [d for d in laws_index.documents if 'Art.' in d.get('citation', '')]\n",
    "sample_law_docs = (stpo_docs or fallback_docs)[:5]\n",
    "\n",
    "label = 'StPO' if stpo_docs else 'Art. (fallback — no StPO found)'\n",
    "print(f'\\n  LAWS — 5 sample docs ({label}):')\n",
    "for i, doc in enumerate(sample_law_docs):\n",
    "    text_preview = doc.get('text', '')[:200].replace('\\n', ' ')\n",
    "    print(f'\\n  [{i+1}] citation : {doc.get(\"citation\", \"?\")}')\n",
    "    for k, v in doc.items():\n",
    "        if k not in ('citation', 'text'):\n",
    "            print(f'       {k:12}: {v}')\n",
    "    print(f'       text (200c): {text_preview}')\n",
    "\n",
    "# Courts: BGE docs\n",
    "bge_docs = [d for d in courts_index.documents if d.get('citation', '').startswith('BGE')]\n",
    "print(f'\\n  COURTS — 5 sample BGE docs (total BGE in index: {len(bge_docs):,}):')\n",
    "for i, doc in enumerate(bge_docs[:5]):\n",
    "    text_preview = doc.get('text', '')[:200].replace('\\n', ' ')\n",
    "    print(f'\\n  [{i+1}] citation : {doc.get(\"citation\", \"?\")}')\n",
    "    for k, v in doc.items():\n",
    "        if k not in ('citation', 'text'):\n",
    "            print(f'       {k:12}: {v}')\n",
    "    print(f'       text (200c): {text_preview}')\n",
    "\n",
    "print(f'\\n{SEP}')\n",
    "print('  END — no changes made')\n",
    "print(SEP)\n",
]

HEADER_SOURCE = [
    "## 13. Corpus Coverage Diagnosis\n",
    "\n",
    "Checks which law abbreviations and court series actually exist in the loaded indices, "
    "scans the data directory for additional files, and samples raw documents. "
    "**No changes made.**"
]

nb = json.load(open(NB_PATH, encoding="utf-8"))

nb["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": HEADER_SOURCE
})
nb["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": SOURCE
})

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

total = len(nb["cells"])
print(f"Done. Notebook now has {total} cells.")
print(f"Coverage diagnosis cells at positions {total-2} and {total-1}.")
