import json

NB_PATH = "c:/Users/david/Desktop/project_ssl/Omnilex-Agentic-Retrieval-Competition/notebooks/02_agentic_retrieval_baseline.ipynb"

SOURCE = [
    "# ── Extended Oracle Recall Sweep — diagnosis only, no pipeline changes ───\n",
    "\n",
    "import re\n",
    "\n",
    "SWEEP_IDS   = ['val_001', 'val_002', 'val_003']\n",
    "K_VALUES    = [10, 50, 100, 500, 1000, 2000]\n",
    "K_DETAIL    = 1000   # rank-position detail at this K\n",
    "MAX_SEARCH  = 2000   # ceiling for rank-position lookup\n",
    "\n",
    "SEP  = '=' * 72\n",
    "sep  = '-' * 72\n",
    "\n",
    "# ── helpers ──────────────────────────────────────────────────────────────\n",
    "\n",
    "def _is_law_citation(cit: str) -> bool:\n",
    "    \"\"\"Heuristic: laws start with Art./§/SR; courts start with BGE or docket.\"\"\"\n",
    "    return bool(re.match(r'(Art\\.|§|SR\\s*\\d)', cit.strip()))\n",
    "\n",
    "\n",
    "def _search_combined(query: str, k: int) -> list[dict]:\n",
    "    \"\"\"Search both indices and return merged result list (deduped by citation).\"\"\"\n",
    "    law_r    = laws_index.search(query, top_k=k)\n",
    "    court_r  = courts_index.search(query, top_k=k)\n",
    "    seen, out = set(), []\n",
    "    for doc in law_r + court_r:\n",
    "        c = doc.get('citation', '')\n",
    "        if c not in seen:\n",
    "            seen.add(c)\n",
    "            out.append(doc)\n",
    "    return out\n",
    "\n",
    "\n",
    "def _rank_in_index(query: str, target_citation: str, index, max_k: int = MAX_SEARCH) -> int | None:\n",
    "    \"\"\"Return 1-based rank of target_citation in index, or None if not found.\"\"\"\n",
    "    results = index.search(query, top_k=max_k)\n",
    "    for rank, doc in enumerate(results, start=1):\n",
    "        if doc.get('citation', '') == target_citation:\n",
    "            return rank\n",
    "    return None\n",
    "\n",
    "\n",
    "# ── load val queries ─────────────────────────────────────────────────────\n",
    "sweep_rows = test_df[test_df['query_id'].isin(SWEEP_IDS)].reset_index(drop=True)\n",
    "\n",
    "print(SEP)\n",
    "print('  EXTENDED ORACLE RECALL SWEEP')\n",
    "print(SEP)\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────\n",
    "# PART 1 — recall curves + rank-position breakdown\n",
    "# ─────────────────────────────────────────────────────────────────────────\n",
    "print('\\n  PART 1 — Oracle recall@K curves and rank positions\\n')\n",
    "\n",
    "all_targeted_rows = []   # collected for Part 2\n",
    "\n",
    "for _, row in sweep_rows.iterrows():\n",
    "    qid      = row['query_id']\n",
    "    query    = row['query']\n",
    "    gold_str = row.get('gold_citations', '')\n",
    "    gold     = [c.strip() for c in gold_str.split(';') if c.strip()]\n",
    "\n",
    "    law_gold   = [c for c in gold if _is_law_citation(c)]\n",
    "    court_gold = [c for c in gold if not _is_law_citation(c)]\n",
    "\n",
    "    print(sep)\n",
    "    print(f'  {qid} — \"{query[:80]}...\"')\n",
    "    print(f'  Gold: {len(gold)} total  ({len(law_gold)} laws, {len(court_gold)} courts)')\n",
    "    print(sep)\n",
    "\n",
    "    # Recall curve\n",
    "    print(f'  {\"K\":>6}  {\"Found\":>6}  {\"Total\":>6}  {\"Recall\":>8}')\n",
    "    print(f'  {\"-\"*6}  {\"-\"*6}  {\"-\"*6}  {\"-\"*8}')\n",
    "    for k in K_VALUES:\n",
    "        combined = _search_combined(query, k)\n",
    "        cit_set  = {d.get('citation', '') for d in combined}\n",
    "        found    = sum(1 for g in gold if g in cit_set)\n",
    "        print(f'  {k:>6}  {found:>6}  {len(gold):>6}  {found/len(gold):>8.1%}')\n",
    "\n",
    "    # Rank-position detail at K_DETAIL\n",
    "    law_results   = laws_index.search(query, top_k=MAX_SEARCH)\n",
    "    court_results = courts_index.search(query, top_k=MAX_SEARCH)\n",
    "    law_cit_rank   = {d.get('citation', ''): i+1 for i, d in enumerate(law_results)}\n",
    "    court_cit_rank = {d.get('citation', ''): i+1 for i, d in enumerate(court_results)}\n",
    "\n",
    "    found_laws   = [(c, law_cit_rank[c])   for c in law_gold   if c in law_cit_rank]\n",
    "    found_courts = [(c, court_cit_rank[c]) for c in court_gold if c in court_cit_rank]\n",
    "    missed_laws   = [c for c in law_gold   if c not in law_cit_rank]\n",
    "    missed_courts = [c for c in court_gold if c not in court_cit_rank]\n",
    "\n",
    "    print(f'\\n  At K={MAX_SEARCH}:')\n",
    "    print(f'    LAWS   found {len(found_laws)}/{len(law_gold)}')\n",
    "    for c, r in sorted(found_laws, key=lambda x: x[1]):\n",
    "        print(f'      rank {r:>5}  {c}')\n",
    "    if missed_laws:\n",
    "        print(f'    LAWS   NOT FOUND in top-{MAX_SEARCH}:')\n",
    "        for c in missed_laws:\n",
    "            print(f'      MISSING  {c}')\n",
    "\n",
    "    print(f'    COURTS found {len(found_courts)}/{len(court_gold)}')\n",
    "    for c, r in sorted(found_courts, key=lambda x: x[1]):\n",
    "        print(f'      rank {r:>5}  {c}')\n",
    "    if missed_courts:\n",
    "        print(f'    COURTS NOT FOUND in top-{MAX_SEARCH}:')\n",
    "        for c in missed_courts:\n",
    "            print(f'      MISSING  {c}')\n",
    "\n",
    "    # Collect for Part 2 targeted queries\n",
    "    for c in gold:\n",
    "        all_targeted_rows.append({'citation': c, 'query': query, 'qid': qid})\n",
    "\n",
    "# ─────────────────────────────────────────────────────────────────────────\n",
    "# PART 2 — targeted exact-string query test\n",
    "# ─────────────────────────────────────────────────────────────────────────\n",
    "print(f'\\n{SEP}')\n",
    "print('  PART 2 — Targeted exact-string query test')\n",
    "print(f'  (searching each gold citation string directly as a query)\\n')\n",
    "print(SEP)\n",
    "\n",
    "SPECIFIC_TARGETED = [\n",
    "    # (query_string, target_citation, index_label, index_obj)\n",
    "    ('Art. 221 Abs. 1',    'Art. 221 Abs. 1 StPO', 'laws',   laws_index),\n",
    "    ('Art. 100 Abs. 1 BGG','Art. 100 Abs. 1 BGG',  'laws',   laws_index),\n",
    "    ('Art. 37 Abs. 1',     'Art. 37 Abs. 1 StBOG', 'laws',   laws_index),\n",
    "    ('BGE 137 IV 122',     'BGE 137 IV 122 E. 6.2','courts', courts_index),\n",
    "    ('1B_90/2021',         '1B_90/2021 E. 2.1',    'courts', courts_index),\n",
    "]\n",
    "\n",
    "# Summary table rows\n",
    "table_rows = []\n",
    "\n",
    "print(f'  {\"Citation\":<35} {\"Index\":>7} {\"ExactRank\":>10} {\"K_needed\":>10} {\"@1000\":>7}')\n",
    "print(f'  {\"-\"*35} {\"-\"*7} {\"-\"*10} {\"-\"*10} {\"-\"*7}')\n",
    "\n",
    "for q_str, target, idx_label, idx_obj in SPECIFIC_TARGETED:\n",
    "    # Find rank using the targeted query string\n",
    "    rank = _rank_in_index(q_str, target, idx_obj, max_k=MAX_SEARCH)\n",
    "\n",
    "    # Find minimum K to retrieve (binary-search style via K_VALUES)\n",
    "    k_needed = None\n",
    "    for k in K_VALUES:\n",
    "        res = idx_obj.search(q_str, top_k=k)\n",
    "        if any(d.get('citation', '') == target for d in res):\n",
    "            k_needed = k\n",
    "            break\n",
    "\n",
    "    at_1000 = 'YES' if rank is not None and rank <= 1000 else 'NO'\n",
    "    rank_str   = str(rank)   if rank     is not None else 'NOT FOUND'\n",
    "    k_need_str = str(k_needed) if k_needed is not None else 'NOT FOUND'\n",
    "\n",
    "    print(f'  {target:<35} {idx_label:>7} {rank_str:>10} {k_need_str:>10} {at_1000:>7}')\n",
    "    table_rows.append((target, idx_label, rank_str, k_need_str, at_1000))\n",
    "\n",
    "    # Show actual top-5 for the targeted query so we can see what IS ranking\n",
    "    top5 = idx_obj.search(q_str, top_k=5)\n",
    "    print(f'    top-5 for query \"{q_str}\":')\n",
    "    for i, d in enumerate(top5):\n",
    "        hit = ' <-- TARGET' if d.get('citation', '') == target else ''\n",
    "        print(f'      {i+1}. {d.get(\"citation\", \"?\")}{hit}')\n",
    "\n",
    "print(f'\\n{SEP}')\n",
    "print('  END — no pipeline changes made')\n",
    "print(SEP)\n",
]

HEADER_SOURCE = [
    "## 12. Extended Oracle Recall Sweep\n",
    "\n",
    "Diagnosis only — no pipeline changes. Computes BM25 oracle recall at multiple K values "
    "and checks whether gold citations are retrievable via exact-string targeted queries."
]

nb = json.load(open(NB_PATH, encoding="utf-8"))

nb["cells"].append({
    "cell_type": "markdown",
    "metadata": {},
    "source": HEADER_SOURCE
})
nb["cells"].append({
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": SOURCE
})

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

total = len(nb["cells"])
print(f"Done. Notebook now has {total} cells.")
print(f"Oracle sweep cells at positions {total-2} and {total-1}.")
